### ISSUE TITLE
TOC Collapsing NB cells

### ISSUE THREAD

**Issue by TRM13** [jupyterlab/jupyterlab-toc#109]
I just upgraded to JupyterLab 1.2.3 (core 4.6.1, nb 6.0.2) all Anaconda. I have to re-install the TOC after upgrades and it works but it is now collapsing the notebook cells when I collapse the menu for the TOC. 

I have to leave all the TOC items fully expanded or the notebook cells disappear. I would like to have the notebook fully expanded and the TOC collapse only itself not hide the cells.

Is there a way to turn this "feature" off? 

Thanks

**Comment by ian-r-rose** [comment]
Hi @TRM13, notebook cell collapsing is an experimental new feature that still has some kinks to be worked out. We will likely make it configurable in an upcoming release, but in the meantime you should be able to roll back by installing the previous version:
`jupyter labextension install @jupyterlab/toc@1.0`

**Comment by TRM13** [comment]
Thanks for the quick response. I didn't know if anyone was aware of that behavior so I thought I should mention it. I can see where it would be useful but just not for what I'm doing at this time LOL. 
I'll use the old version for now. 

Thanks.

**Comment by stefansimik** [comment]
We are using latest JupyterLab 2.0.1 ... 
Is there any version, to which we can rollback?

(despite this feature can be occasionally very useful - , it is very unintuitive and can be destructive, as bad things happened today, in our company. 
**People are deleting notebooks,** because they think these are just some temporary notebooks, which do not contain required code (but code it was just well hidden by TOC and nobody expected this). 

The behavior

**Comment by jasongrout** [comment]
>  Is there any version, to which we can rollback?

I think not for jlab 2.0, at least right now. Perhaps the best way forward is to contribute a PR which turns off the collapsing by default and makes it available via a setting?
