### ISSUE TITLE
Export generators to allow other extensions to use them

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab-toc#119]
Currently the generator functions are not exported at the root index, I suggest we include them as exports. This will allow other extensions to use the built in generators with their own trackers, such as extensions that wrap one of the currently supported file types, but utilize their own trackers for them.

**Comment by kgryte** [comment]
@ajbozarth Do you have an actual example where such generators are needed? I am extremely hesitant to support this without concrete examples (e.g., a public repo or extension in the wild).

Why? Because this significantly increases the extension API surface area, now and in the future as more generators are added, and limits the ability to refactor going forward.

Atm, if someone really wanted to use the current generators, then they could simply walk the filesystem (e.g., `import { createLatexGenerator } from '@jupyterlab/toc/lib/generators/latex';`). Devs can do this right now, but at least we are not guaranteeing anything regarding the API contract and devs would be walking the filesystem at their own risk, thus highlighting that we're not making any guarantees.

**Comment by lresende** [comment]
@ajbozarth would the suggestion above work on your scenario? 

@kgryte, in the case where the above does not work, is there a way to expose `experimental` APIs to allow developers to play/integrate with these extensions and provide feedback? I believe we have similar things in JupyterLab like the `Extension Manager`.

**Comment by ajbozarth** [comment]
I was able to make my extension work using the full path as suggested, though I'm not a fan of such a workaround I agree that expanding the toc api so drastically is potentially not worth it if the workaround exists. I will close my pr and this issue as such
