### ISSUE TITLE
Using toc to jump to the specified content is easy to trigger to edit the target cell

### ISSUE THREAD

**Issue by 935048000** [jupyterlab/jupyterlab-toc#60]
Click the corresponding menu to enter the editing state, click the jump event after the start of automatic editing cells?

**Click the menu - > to jump to the specified content - > edit cell ?**
There is a high probability that the process is this, which should be a bug because the process is so unreasonable.

I just want to jump to the specified content, not edit the header cells.

**Comment by 935048000** [comment]
The problem seems to be on Google Chrome, and I used Firefox to find out that it doesn't happen.It seems like a compatibility issue, but my personal preference for using chrome has disappointed me.

**Comment by kenjioman** [comment]
I think #51 is related? (unless things have changed since when I made the last issue, and you are referring to something else xP).

**Comment by marius311** [comment]
@kenjioman I think this issue is the same as your first point in #51, but the replies by @ian-r-rose sound like maybe he didn't quite understand what you were describing. 

To be clearer for the devs, the problem is this:

![toc](https://user-images.githubusercontent.com/1510968/50588614-c30e5f80-0e37-11e9-9529-1ab66f16c8e1.gif)

You can see that after you enter edit mode of the code cell, clicking on the TOC entries edits the headers, which is probably not what (99% of the time you probably just want to jump around your notebook), and is quite annoying since you then have to go re-evaluate the markdown cell. This is happening with the latest jupyterlab-toc 0.6.0 and jupyterlab 0.35.4.

**Comment by jasongrout** [comment]
Here's a guess about what is going on (I haven't tried anything out, just browsed the source, so I might be way off):

I think the scrolling behavior happens around:
https://github.com/jupyterlab/jupyterlab-toc/blob/fdc5154e72c024adb324c7ef7cc77d849c64b220/src/generators/notebookgenerator/index.ts#L293
My guess is that when the notebook is in edit mode (because you are in a code cell), the active cell is changed, but the notebook *stays* in edit mode. Perhaps to fix this, you need to see if the target cell is a rendered cell, and if it is, switch the notebook to command mode.

**Comment by ian-r-rose** [comment]
Yes, I believe you are right @jasongrout. Thanks for taking a look.

**Comment by kenjioman** [comment]
Thank you @marius311 !  This did capture my original issue, and thanks to all for your continued hard work making this better and better!
