### ISSUE TITLE
Always out of sync with Anaconda

### ISSUE THREAD

**Issue by berniehogan** [jupyterlab/jupyterlab-toc#64]
Having taught Anaconda python over a couple years, this version seems persistently out of sync with Anaconda. Given that Anaconda is the most popular version of jupyterlab by an order of magnitude, it seems entirely unreasonable that there is no clear instructions on how to roll this amazing feature in.

I've tried reverting to previous versions and their dependencies are either too new or too old. It is very frustrating as teaching with jupyterlab is a very important use case. Simplified instructions would also be of great help to students. That being said, I understand the need for advanced development features, but I am surprised that this program constantly needs bleeding edge features that upgrade it outside of the major python market.

**Comment by ian-r-rose** [comment]
I'm sorry you are having a frustrating time with this.

I endeavor to keep this extension up-to-date with the most recent version of JupyterLab. I have no control over the version that is distributed in the main conda channel (though it should be up-to-date with the community versions published on conda-forge and pypi). Since JupyterLab is still a pre-1.-0 project, that usually means we are publishing every couple of months or so.

Is there a particular version of JupyterLab you are targeting? That would be more useful than saying it is always out of sync. In particular, the current version of jupyterlab-toc (v0.6.0) is targeting JupyterLab v0.35.

**Comment by ian-r-rose** [comment]
Closing as answered.
